apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: shwetaliberad/python-django:1.0
        ports:
        - containerPort: 8000