apiVersion: "v1"
kind: Pod
metadata:
  name: test-pod-cmd
spec:
  containers:
    - name: test-container
      image: ubuntu
      command: ["/bin/bash", "-c", "echo Error Level: ${LOG_LEVEL} , Log Location: $(LOG_LOCATION)"]
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log.level
        - name: LOG_LOCATION
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log.location
  restartPolicy: Never
      