apiVersion: "v1"
kind: Pod
metadata:
  name: test-pod-secret-cmd
spec:
  containers:
    - name: test-secret-container
      image: ubuntu
      command: ["/bin/bash", "-c", "echo Username: ${USERNAME}, Password: ${PASSWORD}"]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-pass
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-pass
              key: password
  restartPolicy: Never