apiVersion: v1
kind: Service
metadata:
   name: my-emp
   labels:
     run: my-emp
spec:
   type: NodePort
   ports:
   -  port: 80
      targetPort: 8888
      protocol: TCP
   selector:
     run: my-emp
