apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-emp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: my-emp
    spec:
      containers:
      – image: kavisuresh/Employee
        name: emp
