kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    name: web
  selector:
    name: web
    app: demo