apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    service: auth-service #Service Name
  name: auth-deployment #Deployment Name
   
 
spec: 
  template: 
    metadata: 
      labels: 
        name: auth-selector #Name of selector
    spec: 
      containers: 
        - 
          command: ["/bin/sh","-c"]
          args: ["python run.py"]
 
          env: 
            - 
              name: DB_HOST
              value: "mysqlauth-service.production-cloud.svc.cluster.local:3306"
            - 
              name: DB_USER
              value: admin
            - 
              name: DB_PASS
              value: admin
 
          image: jakirpatel/auth
          name: authservice-container
          ports: 
            - 
              name: auth-port
              containerPort: 5001
              protocol: TCP
 
          resources: 
            limits: 
              cpu: 500m
              memory: 256Mi
            requests: 
              cpu: 250m
              memory: 128Mi
          workingDir: /build/auth_service